// <auto-generated />
using System;
using GymApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApi.Migrations
{
    [DbContext(typeof(GimnasioDbContext))]
    [Migration("20260330220026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymApi.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("RegistradaPorUserId")
                        .HasColumnType("int");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("AsistenciaId")
                        .HasName("PK__Asistenc__72710FA540888A0F");

                    b.HasIndex("RegistradaPorUserId");

                    b.HasIndex(new[] { "SocioId", "FechaHoraEntrada" }, "IX_Asistencias_Socio_Fecha");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("GymApi.Models.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjercicioId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("GrupoMuscular")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Ejercicios_IsActive");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("EjercicioId")
                        .HasName("PK__Ejercici__812226415D746F2B");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Ejercicios_Nombre")
                        .IsUnique();

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("GymApi.Models.Entrenadore", b =>
                {
                    b.Property<int>("EntrenadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntrenadorId"));

                    b.Property<string>("Certificaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],sysdatetime()))", "DF_Entrenadores_FechaIngreso");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Entrenadores_IsActive");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EntrenadorId")
                        .HasName("PK__Entrenad__D0EE85652EA1473D");

                    b.HasIndex(new[] { "UserId" }, "UQ__Entrenad__1788CC4D48775221")
                        .IsUnique();

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("GymApi.Models.Membresia", b =>
                {
                    b.Property<int>("MembresiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembresiaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Membresias_CreatedAt");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<bool>("EsRenovable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Membresias_EsRenovable");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Membresias_IsActive");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MembresiaId")
                        .HasName("PK__Membresi__5AE93097A24A9726");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Membresias_Nombre")
                        .IsUnique();

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("GymApi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Roles_CreatedAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Roles_IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A18772980");

                    b.HasIndex(new[] { "Name" }, "UQ_Roles_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "NormalizedName" }, "UQ_Roles_NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GymApi.Models.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Rutinas_Activa");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Rutinas_CreatedAt");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],sysdatetime()))", "DF_Rutinas_FechaInicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("RutinaId")
                        .HasName("PK__Rutinas__E76E167A53D19555");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex(new[] { "SocioId", "Activa" }, "IX_Rutinas_Socio_Activa");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("GymApi.Models.RutinaEjercicio", b =>
                {
                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int?>("DescansoSegundos")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoObjetivoKg")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.HasKey("RutinaId", "EjercicioId")
                        .HasName("PK__RutinaEj__EF7C341E6FBB979C");

                    b.HasIndex("EjercicioId");

                    b.HasIndex(new[] { "RutinaId", "Orden" }, "IX_RutinaEjercicios_Rutina_Orden");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("GymApi.Models.Socio", b =>
                {
                    b.Property<int>("SocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocioId"));

                    b.Property<decimal?>("AlturaCm")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("EmergenciaNombre")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EmergenciaTelefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],sysdatetime()))", "DF_Socios_FechaRegistro");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Socios_IsActive");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SocioId")
                        .HasName("PK__Socios__165D08BA60246C4F");

                    b.HasIndex(new[] { "UserId" }, "UQ__Socios__1788CC4DD9DB568D")
                        .IsUnique();

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("GymApi.Models.SocioEntrenador", b =>
                {
                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_SocioEntrenador_Activo");

                    b.Property<DateOnly>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],sysdatetime()))", "DF_SocioEntrenador_FechaAsign");

                    b.Property<int>("SocioEntrenadorId")
                        .HasColumnType("int");

                    b.HasKey("SocioId", "EntrenadorId")
                        .HasName("PK__SocioEnt__5B53E0ECB42D3724");

                    b.HasIndex("EntrenadorId");

                    b.ToTable("SocioEntrenador", (string)null);
                });

            modelBuilder.Entity("GymApi.Models.SocioMembresium", b =>
                {
                    b.Property<int>("SocioMembresiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocioMembresiaId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_SocioMembresia_CreatedAt");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("SocioMembresiaId")
                        .HasName("PK__SocioMem__F467686A03AFAA8F");

                    b.HasIndex("MembresiaId");

                    b.HasIndex(new[] { "Estado", "FechaFin" }, "IX_SocioMembresia_Estado_FechaFin");

                    b.HasIndex(new[] { "SocioId" }, "IX_SocioMembresia_Socio");

                    b.ToTable("SocioMembresia");
                });

            modelBuilder.Entity("GymApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Users_CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Users_IsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C40CB1A69");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "NormalizedEmail" }, "UQ_Users_NormalizedEmail")
                        .IsUnique();

                    b.HasIndex(new[] { "NormalizedUserName" }, "UQ_Users_NormalizedUserName")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ_Users_UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymApi.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysdatetime())", "DF_UserRoles_AssignedAt");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF2760ADD025FC37");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRoles_RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("GymApi.Models.VSocioUltimaMembresium", b =>
                {
                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Membresia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vSocioUltimaMembresia", (string)null);
                });

            modelBuilder.Entity("GymApi.Models.Asistencia", b =>
                {
                    b.HasOne("GymApi.Models.User", "RegistradaPorUser")
                        .WithMany("Asistencia")
                        .HasForeignKey("RegistradaPorUserId")
                        .HasConstraintName("FK_Asistencias_UsuarioReg");

                    b.HasOne("GymApi.Models.Socio", "Socio")
                        .WithMany("Asistencia")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Asistencias_Socio");

                    b.Navigation("RegistradaPorUser");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymApi.Models.Entrenadore", b =>
                {
                    b.HasOne("GymApi.Models.User", "User")
                        .WithOne("Entrenadore")
                        .HasForeignKey("GymApi.Models.Entrenadore", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Entrenadores_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApi.Models.Rutina", b =>
                {
                    b.HasOne("GymApi.Models.Entrenadore", "Entrenador")
                        .WithMany("Rutinas")
                        .HasForeignKey("EntrenadorId")
                        .HasConstraintName("FK_Rutinas_Entr");

                    b.HasOne("GymApi.Models.Socio", "Socio")
                        .WithMany("Rutinas")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Rutinas_Socio");

                    b.Navigation("Entrenador");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymApi.Models.RutinaEjercicio", b =>
                {
                    b.HasOne("GymApi.Models.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RutinaEj_Ejercicio");

                    b.HasOne("GymApi.Models.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RutinaEj_Rutina");

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("GymApi.Models.Socio", b =>
                {
                    b.HasOne("GymApi.Models.User", "User")
                        .WithOne("Socio")
                        .HasForeignKey("GymApi.Models.Socio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Socios_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApi.Models.SocioEntrenador", b =>
                {
                    b.HasOne("GymApi.Models.Entrenadore", "Entrenador")
                        .WithMany("SocioEntrenadors")
                        .HasForeignKey("EntrenadorId")
                        .IsRequired()
                        .HasConstraintName("FK_SocioEntrenador_Entr");

                    b.HasOne("GymApi.Models.Socio", "Socio")
                        .WithMany("SocioEntrenadors")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SocioEntrenador_Socio");

                    b.Navigation("Entrenador");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymApi.Models.SocioMembresium", b =>
                {
                    b.HasOne("GymApi.Models.Membresia", "Membresia")
                        .WithMany("SocioMembresia")
                        .HasForeignKey("MembresiaId")
                        .IsRequired()
                        .HasConstraintName("FK_SocioMembresia_Membresia");

                    b.HasOne("GymApi.Models.Socio", "Socio")
                        .WithMany("SocioMembresia")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SocioMembresia_Socio");

                    b.Navigation("Membresia");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymApi.Models.UserRole", b =>
                {
                    b.HasOne("GymApi.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Role");

                    b.HasOne("GymApi.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApi.Models.Ejercicio", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("GymApi.Models.Entrenadore", b =>
                {
                    b.Navigation("Rutinas");

                    b.Navigation("SocioEntrenadors");
                });

            modelBuilder.Entity("GymApi.Models.Membresia", b =>
                {
                    b.Navigation("SocioMembresia");
                });

            modelBuilder.Entity("GymApi.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GymApi.Models.Rutina", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("GymApi.Models.Socio", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("Rutinas");

                    b.Navigation("SocioEntrenadors");

                    b.Navigation("SocioMembresia");
                });

            modelBuilder.Entity("GymApi.Models.User", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("Entrenadore");

                    b.Navigation("Socio");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
